### ISSUE TITLE
Audio Super Resolution install fails with Python 3.12

### ISSUE THREAD

**Issue by mekler22** [haoheliu/versatile_audio_super_resolution#60]
I get this error, which I suspect is related to deprecated functions in Python 3.12. Can you fix the code so that it will work with Python 3.12?

```
Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "C:\ProgramData\miniconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\ProgramData\miniconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\miniconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "C:\ProgramData\miniconda3\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ProgramData\miniconda3\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\fox\AppData\Local\Temp\pip-build-env-orux7t77\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\fox\AppData\Local\Temp\pip-build-env-orux7t77\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\fox\AppData\Local\Temp\pip-build-env-orux7t77\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by GoombaProgrammer** [comment]
Use a conda env with python 3.9

**Comment by tecspda** [comment]
Work with python3.11-env in my ubuntu

**Comment by xandark** [comment]
I too wish that this worked with modern Python versions (now that distutils has been deprecated and removed). 

I realize that this is not a fix, but my work around is to use [uv](https://docs.astral.sh/uv/), an extremely fast package-and-Python manager. After installing uv, then this one command will install audiosr as a tool along with all dependencies and using only Python 3.11, which has distutils:

`uv tool install --python=3.11 git+https://github.com/haoheliu/versatile_audio_super_resolution.git`

**Comment by littleji** [comment]
> I too wish that this worked with modern Python versions (now that distutils has been deprecated and removed).
> 
> I realize that this is not a fix, but my work around is to use [uv](https://docs.astral.sh/uv/), an extremely fast package-and-Python manager. After installing uv, then this one command will install audiosr as a tool along with all dependencies and using only Python 3.11, which has distutils:
> 
> `uv tool install --python=3.11 git+https://github.com/haoheliu/versatile_audio_super_resolution.git`
> 
> UPDATE:
> 
> The previous command will _install_ it successfully but executing audiosr results in a similar stopping error by not being able to `import pkg_resources`, just like the OP's reported error. The difference here is that the error is only slightly changed:
> 
> $ audiosr
> Traceback (most recent call last):
>   File "/home/user/.local/bin/audiosr", line 5, in <module>
>     from audiosr import super_resolution, build_model, save_wave, get_time, read_list
>   File "/home/user/.local/share/uv/tools/audiosr/lib/python3.11/site-packages/audiosr/__init__.py", line 1, in <module>
>     from .utils import seed_everything, save_wave, get_time, get_duration, read_list
>   File "/home/user/.local/share/uv/tools/audiosr/lib/python3.11/site-packages/audiosr/utils.py", line 17, in <module>
>     from librosa.filters import mel as librosa_mel_fn
>   File "/home/user/.local/share/uv/tools/audiosr/lib/python3.11/site-packages/librosa/__init__.py", line 209, in <module>
>     from . import core
>   File "/home/user/.local/share/uv/tools/audiosr/lib/python3.11/site-packages/librosa/core/__init__.py", line 5, in <module>
>     from .convert import *  # pylint: disable=wildcard-import
>     ^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.local/share/uv/tools/audiosr/lib/python3.11/site-packages/librosa/core/convert.py", line 7, in <module>
>     from . import notation
>   File "/home/user/.local/share/uv/tools/audiosr/lib/python3.11/site-packages/librosa/core/notation.py", line 8, in <module>
>     from ..util.exceptions import ParameterError
>   File "/home/user/.local/share/uv/tools/audiosr/lib/python3.11/site-packages/librosa/util/__init__.py", line 78, in <module>
>     from .files import *  # pylint: disable=wildcard-import
>     ^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.local/share/uv/tools/audiosr/lib/python3.11/site-packages/librosa/util/files.py", line 10, in <module>
>     from pkg_resources import resource_filename
> ModuleNotFoundError: No module named 'pkg_resources'

by adding the '--with setuptools', seemed fix your problem(also mine) `uv tool install --python=3.11 git+https://github.com/haoheliu/versatile_audio_super_resolution.git --with setuptools`

**Comment by hamidmashhouri** [comment]
I try to install local drive but :

`D:\New` folder (2)>uv tool install  --python=3.11  git+https://github.com/haoheliu/versatile_audio_super_resolution.git  --with setuptools  --with matplotlib
'uv' is not recognized as an internal or external command,
operable program or batch file.``

Win 11 and python 3.11.9

**Comment by xandark** [comment]
> I try to install local drive but

uv needs to be installed separate from Python. See this for what uv is: https://docs.astral.sh/uv/

If you scroll down on the page, this is the install instructions for getting uv onto your machine:

`powershell -ExecutionPolicy ByPass -c "irm https://astral.sh/uv/install.ps1 | iex"`
