### ISSUE TITLE
[enforce fail at alloc_cpu.cpp:121] data. DefaultCPUAllocator: not enough memory

### ISSUE THREAD

**Issue by liups233** [haoheliu/versatile_audio_super_resolution#82]
Sorry I am new here, just trying to improve my 128 kbps music files. But my 32G ram seems not enough, and my computer becomes extremely slow running this program. Any advice for me

logs are below
```
(audiosr) PS C:\Users\Liups233> audiosr -i C:\Users\Liups233\Desktop\L.wav
C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\huggingface_hub\file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
merges.txt: 100%|████████████████████████████████████████████████████████████████████| 456k/456k [00:00<00:00, 956kB/s]
C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Liups233\.cache\huggingface\hub\models--roberta-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
tokenizer_config.json: 100%|████████████████████████████████████████████████████████| 25.0/25.0 [00:00<00:00, 12.5kB/s]
config.json: 100%|█████████████████████████████████████████████████████████████████████| 481/481 [00:00<00:00, 240kB/s]
C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Loading AudioSR: basic
Loading model on cpu
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
pytorch_model.bin:  45%|██████████████████████████▍                               | 2.81G/6.18G [01:33<01:15, 44.6MB/s]Error while downloading from https://huggingface.co/haoheliu/audiosr_basic/resolve/main/pytorch_model.bin: HTTPSConnectionPool(host='cas-bridge.xethub.hf.co', port=443): Read timed out.
Trying to resume download...
pytorch_model.bin:  45%|██████████████████████████▍                               | 2.81G/6.18G [01:46<01:15, 44.6MB/s]Error while downloading from https://huggingface.co/haoheliu/audiosr_basic/resolve/main/pytorch_model.bin: HTTPSConnectionPool(host='cas-bridge.xethub.hf.co', port=443): Read timed out.
Trying to resume download...
pytorch_model.bin: 100%|██████████████████████████████████████████████████████████| 6.18G/6.18G [01:35<00:00, 29.4MB/s]
pytorch_model.bin:  55%|███████████████████████████████▋                          | 3.38G/6.18G [02:02<10:07, 4.61MB/s]
pytorch_model.bin:  45%|██████████████████████████▍                               | 2.81G/6.18G [03:48<04:34, 12.3MB/s]
C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Liups233\.cache\huggingface\hub\models--haoheliu--audiosr_basic. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torch\functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4324.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torchaudio\transforms\_transforms.py:581: UserWarning: Argument 'onesided' has been deprecated and has no influence on the behavior of this module.
  warnings.warn(
DiffusionWrapper has 258.20 M params.
C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torch\nn\utils\weight_norm.py:144: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torchaudio\_backend\utils.py:213: UserWarning: In 2.9, this function's implementation will be changed to use torchaudio.load_with_torchcodec` under the hood. Some parameters like ``normalize``, ``format``, ``buffer_size``, and ``backend`` will be ignored. We recommend that you port your code to rely directly on TorchCodec's decoder instead: https://docs.pytorch.org/torchcodec/stable/generated/torchcodec.decoders.AudioDecoder.html#torchcodec.decoders.AudioDecoder.
  warnings.warn(
 Warning: audio is longer than 10.24 seconds, may degrade the model performance. It's recommand to truncate your audio to 5.12 seconds before input to AudioSR to get the best performance.
Traceback (most recent call last):
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\audiosr\__main__.py", line 147, in <module>
    waveform = super_resolution(
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\audiosr\pipeline.py", line 195, in super_resolution
    waveform = latent_diffusion.generate_batch(
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torch\utils\_contextlib.py", line 120, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\audiosr\latent_diffusion\models\ddpm.py", line 1493, in generate_batch
    z, c = self.get_input(
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\audiosr\latent_diffusion\models\ddpm.py", line 837, in get_input
    encoder_posterior = self.encode_first_stage(x)
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\audiosr\latent_diffusion\models\ddpm.py", line 935, in encode_first_stage
    return self.first_stage_model.encode(x)
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\audiosr\latent_encoder\autoencoder.py", line 106, in encode
    h = self.encoder(x)
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\audiosr\latent_diffusion\modules\diffusionmodules\model.py", line 531, in forward
    hs.append(self.down[i_level].downsample(hs[-1]))
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\audiosr\latent_diffusion\modules\diffusionmodules\model.py", line 91, in forward
    x = self.conv(x)
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torch\nn\modules\module.py", line 1773, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torch\nn\modules\module.py", line 1784, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torch\nn\modules\conv.py", line 548, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torch\nn\modules\conv.py", line 543, in _conv_forward
    return F.conv2d(
RuntimeError: [enforce fail at alloc_cpu.cpp:121] data. DefaultCPUAllocator: not enough memory: you tried to allocate 3907518464 bytes.
```

**Comment by liups233** [comment]
Problem solved. I install CUDA toolkit and torch that supported, and used `-d cuda:0` to run audiosr. But an error occurred after DDIM Sampler: `AttributeError: 'numpy.ndarray' object has no attribute 'cpu'`. 
Logs are below
```
(audiosr) C:\Users\Liups233\Desktop>audiosr -i C:\Users\Liups233\Desktop\output\out_00019.wav -d cuda:0
C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\huggingface_hub\file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Loading AudioSR: basic
Loading model on cuda:0
C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torch\functional.py:554: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4324.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torchaudio\transforms\_transforms.py:581: UserWarning: Argument 'onesided' has been deprecated and has no influence on the behavior of this module.
  warnings.warn(
DiffusionWrapper has 258.20 M params.
C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torch\nn\utils\weight_norm.py:144: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\torchaudio\_backend\utils.py:213: UserWarning: In 2.9, this function's implementation will be changed to use torchaudio.load_with_torchcodec` under the hood. Some parameters like ``normalize``, ``format``, ``buffer_size``, and ``backend`` will be ignored. We recommend that you port your code to rely directly on TorchCodec's decoder instead: https://docs.pytorch.org/torchcodec/stable/generated/torchcodec.decoders.AudioDecoder.html#torchcodec.decoders.AudioDecoder.
  warnings.warn(
Running DDIM Sampling with 50 timesteps
DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████| 50/50 [00:04<00:00, 10.08it/s]
 Don't forget to try different seeds by setting --seed <int> so that AudioSR can have optimal performance on your hardware.
Save audio to ./output\09_09_2025_01_59_24\out_00019_AudioSR_Processed_48K.wav.
Traceback (most recent call last):
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\audiosr\__main__.py", line 155, in <module>
    save_wave(waveform, inputpath=input_file, savepath=save_path, name=name, samplerate=sample_rate)
  File "C:\Users\Liups233\.conda\envs\audiosr\lib\site-packages\audiosr\utils.py", line 316, in save_wave
    data_to_save = waveform[i].T.cpu().numpy()
AttributeError: 'numpy.ndarray' object has no attribute 'cpu'
```

**Comment by liups233** [comment]
Problem solved by installing older CUDA Toolkie

**Comment by lubosz** [comment]
> Problem solved by installing older CUDA Toolkie

There is no way this was solved by changing any CUDA versions.
I have tried all PyTorch versions ranging from `1.13.1` to `2.9.0`, using CUDA 11 and 12 accordingly. Also tried environments using Python `3.13`, `3.11` and `3.10`.

The issue remains.

> `AttributeError: 'numpy.ndarray' object has no attribute 'cpu'`

This issue is an regression introduced in 12a5067ec60d942bb6e893d7f6e26ea19366ccf3
This patch breaks the `save_wave` function with the non-chunked path, expecting a torch tensor, but the non-chunked `super_resolution` returns a numpy array.
The non-chunked functions converts the waveform to numpy here https://github.com/haoheliu/versatile_audio_super_resolution/blob/main/audiosr/latent_diffusion/models/ddpm.py#L928

So you probably avoided the issue by using the chunked `super_resolution_long_audio` path.
